spring:
  datasource:
    url: jdbc:mysql://localhost:3306/flyway-demo?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
  jpa:
    generate-ddl: true
    show-sql: true
    database: mysql
